### ISSUE TITLE
overall improvement in Updates page

### ISSUE THREAD

**Issue by codeperfectplus** [Py-Contributors/py-contributors.github.io#8]
What can you improve

- Card style
- Card background color
- Button Color size & location
- Any Background if you like

Check https://jekyllrb.com/ documentation and liquid tags once.

base file - _layout/blog.html
updates page HTML file >> updates/index.html

* Command to Run server locally for testing.
```bash
gem install bundler jekyll
bundle exec jekyll serve
```
If you have telegram/discord.
- Discord - soundsLikecrazy#9794
- Telegram -https://t.me/pyContributors2

Happy Coding,

**Comment by codeperfectplus** [comment]
Sorry I haven't anything from your side @aditimaurya. So Assigning this task to @reveurguy .

we have other project too on frontend,
Happy Coding,

**Comment by aditimaurya** [comment]
@codePerfectPlus  I was actually reading the doccuments, and didn't know I have to respond here also. I have responded on the previous issue where you have told me that you've assigned this one. Anyway, may be I'm new so that's why I don't know much about the workflow in an organisation. If you have other issues then do let me know. If they are related to hacktoberfest then please do assign me. I'll give my best. Thankyou !

**Comment by reveurguy** [comment]
@aditimaurya there is a new issue for logo. you can check that.

**Comment by aditimaurya** [comment]
@reveurguy sure!
